# Set some names, nothing weird here
name: Automated Upload Workflow
run-name: Workflow to generate and upload content
on: [push] # Apply workflow on git push only
jobs:
  Run-Bash-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code # checkout the code first
        uses: actions/checkout@v4
      - name: Install Pelican
        run: sudo apt-get install pelican markdown
      - name: Check versions
        run: |
          pip3 install pelican[markdown]
          pelican --version
          markdown --version

