# Set some names, nothing weird here
name: Automated Upload Workflow
run-name: Workflow to generate and upload content
on: [push] # Apply workflow on git push only

env:
  OUTPUT_DIR: output/
  S3_BUCKET: iainrawlings.com
  CLOUDFRONT_DIST: E1KXVSFIKUXWDG

jobs:
  Tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_GHA_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GHA_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Checkout Repository Code # checkout the code first
        uses: actions/checkout@v4
      - name: Install Pelican
        run: pip3 install pelican[markdown]
      - name: Create static content from output
        run: pelican content
      - name: Check output exists
        run: ls output
      - name: Upload content to s3
        run: aws s3 cp $OUTPUT_DIR s3://$S3_BUCKET --recursive
      - name: Inv_cf_cache
        id: cf_invalidation_request
        run: |
          rtn_str=$(aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DIST }} --paths "/" | jq -r  ".Invalidation.Id")
          echo "inv_request=$rtn_str" >> $GITHUB_OUTPUT

      - name: Echo invalidation request ID
        run: echo "Invlaidation Request is ${{ steps.cf_invalidation_request.output }}"
      


          
