# Set some names, nothing weird here
name: Automated Upload Workflow
run-name: Workflow to generate and upload content
on: [push] # Apply workflow on git push only

env:
  OUTPUT_DIR: output/
  S3_BUCKET: iainrawlings.com
  CLOUDFRONT_DIST: E1KXVSFIKUXWDG

jobs:
  Tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_GHA_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GHA_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Checkout repository code # checkout the code first
        uses: actions/checkout@v4
      - name: Install Pelican
        run: pip3 install pelican[markdown]
      - name: Create static content from output
        run: pelican content
      - name: Check output exists
        run: |
        ls output
        aws configure get region
      - name: Upload content to s3
        run: aws s3 cp $OUTPUT_DIR s3://$S3_BUCKET --recursive
      - name: Inv_cf_cache
        id: cf_invalidation_request
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/" | jq -r  ".Invalidation.Id" >> $GITHUB_OUTPUT # check this syntax
      - name: echo github output
        run: echo $GITHUB_OUTPUT
        # run: echo "Invalidating cloudfront cache..."
      # - name: Await_cf_inv
        # run: | # we need to talk about this tomorrow, I think I've got close to the right syntax but since this can get pretty confusing we'll check it over.
        # aws cloudfront wait invalidation-completed --id ${{ steps.Inv_cf_cache.outputs.cf_invalidation_request }} --distribution-id $CLOUDFRONT_DIST
        # echo "Invalidation request: ${{ steps.Inv_cf_cache.outputs.cf_invalidation_request }} Completed. Upload Complete & Cache Reset"


          
